cc_binary(
    name = "day1",
    srcs = ["day1.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day2",
    srcs = ["day2.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day3",
    srcs = ["day3.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day4",
    srcs = ["day4.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day5",
    srcs = ["day5.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day6",
    srcs = ["day6.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

