cc_binary(
    name = "day1",
    srcs = ["day1.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day2",
    srcs = ["day2.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day3",
    srcs = ["day3.cc"],
    deps = ["@cxxopts//:cxxopts"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day4",
    srcs = ["day4.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day5",
    srcs = ["day5.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day6",
    srcs = ["day6.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day7",
    srcs = ["day7.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day8",
    srcs = ["day8.cc"],
    deps = ["@cxxopts//:cxxopts",
            "//inputs:data"
            ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_library(
    name = "utils",
    srcs = ["utils.cc", "utils.h"],
    copts = [
        "-std=c++2a", "-O3"
    ],
)


cc_binary(
    name = "day9",
    srcs = ["day9.cc"],
    deps = [
        "//inputs:data",
        ":utils",
        "@cxxopts//:cxxopts",
        "@boost//:functional"
    ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)

cc_binary(
    name = "day10",
    srcs = ["day10.cc"],
    deps = [
        ":utils",
        "@cxxopts//:cxxopts",
    ],
    copts = [
        "-std=c++2a", "-O3"
    ],
)